name: pbiotools
channels:
  - defaults
  - conda-forge
  - bioconda
dependencies:
  - python
  - appdirs # ?
  - biopython
  - cmdstanpy
  - dask # ?
  - fastparquet # ?
  - joblib
  - matplotlib-base
  - matplotlib-venn # ?
  - more-itertools
  - mygene # ?
  - numpy
  - openpyxl # ?
  - pandas
  - pip
  - pybedtools # ?
  - pyensembl # ?
  - pytest
  - pyyaml
  - seaborn
  - scikit-learn
  - scipy
  - statsmodels
  - tqdm
  - pip:
      - pysam==0.20.0 # with Samtools-1.16.1
