name: pbiotools
channels:
  - defaults
  - conda-forge
  - bioconda
dependencies:
  - python=3.10.6
  - cmdstanpy # 1.0.8
  - dask
  - scikit-learn
  - appdirs # ???
  - tqdm
  - mygene # ???
  - openpyxl # ???
  - fastparquet
  - more-itertools
  - matplotlib-base
  - matplotlib-venn
  - seaborn
  - pybedtools # ???
  - biopython
  - pyensembl # ???
  - pytest
  - pip
  - pip:
      - pysam==0.20.0 # with Samtools-1.16.1
