name: pbiotools
channels:
  - defaults
  - conda-forge
  - bioconda
dependencies:
  - python
  - biopython
  - joblib
  - matplotlib-base
  - mygene
  - numpy
  - pandas
  - pip
  - pysam
  - pytest
  - seaborn
  - scikit-learn
  - scipy
  - tqdm
